series: Basic C++
title: The Stack and the Heap
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Take advantage of the new and delete keywords to manage objects on the heap.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Pointers
  - series: Basic C++
    title: Constructors and Destructors